name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download and Extract FFmpeg
        run: |
          Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z" -OutFile "ffmpeg.7z"
          7z x ffmpeg.7z -oFFMPEG
          $extracted_folder = Get-ChildItem -Path "FFMPEG" -Directory | Select-Object -First 1
          $bin_path = Join-Path -Path $extracted_folder.FullName -ChildPath "bin\*"
          New-Item -ItemType Directory -Force -Path "ffmpeg_bin"
          Move-Item -Path $bin_path -Destination "ffmpeg_bin"
        shell: powershell

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller yt-dlp customtkinter

      - name: Get CustomTkinter path
        id: customtkinter_path
        run: |
          $path = (Get-Command python).Source | Split-Path | Join-Path -ChildPath "Lib\site-packages\customtkinter"
          echo "path=$path" >> $env:GITHUB_OUTPUT
        shell: powershell

      - name: Build the executable
        run: |
          pyinstaller --onefile --windowed --name "YouTubeDownloader" \
            --hidden-import "customtkinter" \
            --add-data "${{ steps.customtkinter_path.outputs.path }};customtkinter/" \
            --add-data "ffmpeg_bin/ffmpeg.exe:." \
            --add-data "ffmpeg_bin/ffprobe.exe:." \
            main.py
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouTubeDownloader-Windows
          path: dist/YouTubeDownloader.exe
